# Generated by Django 4.2.23 on 2025-08-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_course_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
